name: factory

on:
  workflow_dispatch:        # manual Run button
  schedule:
    - cron: '0 21 * * *'    # every day 21:00 KST

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣  Get repo code
      - uses: actions/checkout@v4

      # 2️⃣  Install Ollama + free Phi-3-mini model (≈1.8 GB)
      - name: Install Ollama and model
        run: |
          curl -fsSL https://ollama.ai/install.sh | sh
          ollama pull phi3

      # 3️⃣  Pick a topic from Reddit
      - name: Pick topic
        id: topic
        run: |
          python - <<'PY'
          import requests, random, os, json
          subs = ["ADHD", "GetStudying", "biology"]
          hdr  = {"User-Agent": "snap-study-bot"}
          titles = []
          for s in subs:
              j = requests.get(f"https://www.reddit.com/r/{s}/top.json?t=day&limit=20",
                               headers=hdr).json()
              titles += [c["data"]["title"] for c in j["data"]["children"]]
          choice = random.choice(titles)
          print(f"::set-output name=text::{choice}")
          PY

      # 4️⃣  Generate dashboard markdown
      - name: Write dashboard
        run: |
          ollama run phi3 "Write a focused Notion markdown study dashboard about '${{ steps.topic.outputs.text }}'." > dashboard.md

      # 5️⃣  Zip it
      - name: Zip dashboard
        run: zip product.zip dashboard.md

      # 6️⃣  Hand zip back to you
      - uses: actions/upload-artifact@v4
        with:
          name: product
          path: product.zip
