# .github/workflows/factory.yml
name: 🎉 Daily Study Dashboard Factory

on:
  schedule:
    - cron: '0 12 * * *'  # 21:00 KST
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      KOFI_TOKEN: ${{ secrets.KOFI_TOKEN }}
      KOFI_PRODUCT_ID: ${{ secrets.KOFI_PRODUCT_ID }}
      KOFI_MEMBERS_API: ${{ secrets.KOFI_MEMBERS_API }}
      RESEND_API_KEY: ${{ secrets.RESEND_API_KEY }}

    steps:
      - name: ✅ Checkout repo
        uses: actions/checkout@v4

      - name: ✨ Install Python deps
        run: |
          python -m pip install --upgrade pip
          pip install ctransformers==0.2.27 accelerate requests

      - name: 💾 Prepare model directory
        run: |
          rm -rf "$RUNNER_TEMP/model"
          mkdir -p "$RUNNER_TEMP/model"

      - name: ⬇️ Download TinyLlama model
        run: |
          curl -L "https://huggingface.co/TheBloke/TinyLlama-1.1B-Chat-v1.0-GGUF/resolve/main/tinyllama-1.1b-chat-v1.0.q4_K_M.gguf" \
            -o "$RUNNER_TEMP/model/tinyllama.gguf"

      - name: 📖 Pick Topic & Generate Dashboard
        run: |
          python3 -c """
import requests, random, subprocess
subs = ["ADHD", "GetStudying", "biology"]
titles = []
for sub in subs:
  r = requests.get(f'https://www.reddit.com/r/{sub}/top.json?t=day&limit=20', headers={'User-agent': 'studybot'})
  titles.extend([i['data']['title'] for i in r.json()['data']['children']])
topic = random.choice(titles)
prompt = f'''You are a study coach.\nWrite a focused Notion markdown study dashboard about "{topic}".\nInclude:\n- H1 title\n- 7-day countdown table\n- daily checklist\n- habit tracker\n- reflection section\nOutput ONLY markdown.'''
from ctransformers import AutoModelForCausalLM
llm = AutoModelForCausalLM.from_pretrained("$RUNNER_TEMP/model/tinyllama.gguf", model_type="llama")
md = llm(prompt)
with open("dashboard.md", "w") as f: f.write(md.strip())
"""

      - name: 🔐 Zip dashboard
        run: zip product.zip dashboard.md

      - name: 📁 Upload zip artifact
        uses: actions/upload-artifact@v4
        with:
          name: dashboard-zip
          path: product.zip

      - name: 🔄 Update Ko-fi product
        run: bash scripts/update_kofi.sh

      - name: 📧 Email members
        run: python3 scripts/email_members.py
